services:
  backend:
    build:
      context: ./backend
      target: production
    environment:
      - NODE_ENV=production
    volumes: [] # Remove development volumes

  frontend:
    build:
      context: ./frontend
      target: production
    environment:
      - NODE_ENV=production
    volumes: [] # Remove development volumes
  # ai-module:
  #   # Production settings for AI module
  #   environment:
  #     - HF_HOME=/tmp/huggingface
  #     - PYTHONPATH=/app

  # volumes:
  #   postgres_data:
  #     driver: local
