services:
  backend:
    build:
      context: ./backend
      target: development
    container_name: spoon-backend
    ports:
      - "3000:3000" # NestJS defaults to 3000 inside container
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: spoon-frontend
    ports:
      - "8000:3000" # Next.js dev server
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

networks:
  default:
    name: spoon-network