services:
  db:
    image: postgres:latest
    container_name: spoon-db
    environment:
      POSTGRES_USER: spoon_db
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spoon_db
    ports:
      - "5432:5432"
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      target: development
    container_name: spoon-backend
    ports:
      - "3000:3000" # NestJS defaults to 3000 inside container
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: spoon-frontend
    ports:
      - "8000:3000" # Next.js dev server
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

  # ai-module:
  #   build:
  #     context: ./ai-module
  #   container_name: spoon-ai-module
  #   ports:
  #     - "7860:7860" # FastAPI + GPT-2 service
  #   volumes:
  #     - ./ai-module:/app
  #   restart: unless-stopped
  #   environment:
  #     - HF_HOME=/tmp/huggingface

networks:
  default:
    name: spoon-network